spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost/imooc_waimai?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null        # 全局注解，表示返回转json时去掉为null的元素，如果想让某个为null的元素返回，可以给它一个初始值
server:
  context-path: /sell

